=== honeypotio/match_schema/enrich_person_response.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "person": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "additionalProperties": false,
      "definitions": {
      },
      "id": "person.schema.json",
      "properties": {
        "email": {
          "id": "/properties/email",
          "type": "string"
        },
        "experienceEntries": {
          "additionalItems": false,
          "id": "/properties/experienceEntries",
          "items": {
            "additionalProperties": false,
            "id": "/properties/experienceEntries/items",
            "properties": {
              "custom_company": {
                "id": "/properties/experienceEntries/items/properties/custom_company",
                "type": "string"
              },
              "description": {
                "id": "/properties/experienceEntries/items/properties/description",
                "type": [
                  "string",
                  "null"
                ]
              },
              "end_year": {
                "id": "/properties/experienceEntries/items/properties/end_year",
                "type": [
                  "integer",
                  "null"
                ]
              },
              "position": {
                "id": "/properties/experienceEntries/items/properties/position",
                "type": "string"
              },
              "start_year": {
                "id": "/properties/experienceEntries/items/properties/start_year",
                "type": "integer"
              },
              "technologies": {
                "additionalItems": false,
                "id": "/properties/experienceEntries/items/properties/technologies",
                "items": {
                },
                "type": "array"
              }
            },
            "type": "object"
          },
          "type": "array"
        },
        "id": {
          "id": "/properties/id",
          "type": "string"
        },
        "refId": {
          "type": [
            "integer",
            "string"
          ]
        },
        "name": {
          "id": "/properties/name",
          "type": "string"
        },
        "location": {
          "id": "/properties/location",
          "type": "string"
        },
        "summary": {
          "id": "/properties/summary",
          "type": "string"
        },
        "resumeUrl": {
          "type": "string",
          "format": "uri"
        },
        "profileUrls": {
          "additionalItems": false,
          "id": "/properties/profileUrls",
          "items": {
            "id": "/properties/profileUrls/items",
            "type": "string"
          },
          "type": "array"
        },
        "skills": {
          "additionalItems": false,
          "id": "/properties/skills",
          "items": {
            "id": "/properties/skills/items",
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    }
  },
  "id": "enrich_person_response.schema.json",
  "properties": {
    "person": {
      "$ref": "#/definitions/person"
    },
    "status": {
      "default": "found",
      "id": "/properties/status",
      "type": "string"
    },
    "match_request_id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/match_request_id",
      "type": "string"
    },
    "total_count": {
      "id": "/properties/total_count",
      "type": "number"
    }
  },
  "required": [
    "person",
    "status",
    "total_count",
    "match_request_id"
  ],
  "type": "object"
}

=== honeypotio/match_schema/enrich_person_response.example.json
{
  "match_request_id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "total_count": 1,
  "status": "found",
  "person": {
    "id": "e78f3057-8b3a-462e-b257-257d5251ad2b",
    "name": "Hugo Duksis",
    "email": "hugo@honeypot.io",
    "profileUrls": [
      "https://linkedin.com/in/duksis",
      "https://github.com/duksis",
      "https://twitter.com/duksis"
    ],
    "skills": ["backbone.js", "react.js", "flux"],
    "experienceEntries": [
      {
        "position": "airbaltic",
        "description": null,
        "custom_company": "flight support specialist",
        "technologies": [],
        "start_year": 2010,
        "end_year": 2013
      },
      {
        "position": "accenture",
        "description": null,
        "custom_company": "web developer",
        "technologies": [],
        "start_year": 2015,
        "end_year": null
      }
    ]
  }
}
