=== honeypotio/match_schema/enrich_company_response.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "company": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "additionalProperties": false,
      "definitions": {
      },
      "id": "company.schema.json",
      "properties": {
        "id": {
          "id": "/properties/id",
          "type": "string"
        },
        "location": {
          "additionalItems": false,
          "id": "/properties/location",
          "items": {
            "id": "/properties/location/items",
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "id": "/properties/name",
          "type": "string"
        },
        "profileUrls": {
          "additionalItems": false,
          "id": "/properties/profileUrls",
          "items": {
            "id": "/properties/profileUrls/items",
            "type": "string"
          },
          "type": "array"
        },
        "url": {
          "id": "/properties/url",
          "type": "string"
        },
        "positions": {
          "id": "/properties/positions",
          "items": {
            "id": "/properties/positions/items",
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    }
  },
  "id": "enrich_company_response.schema.json",
  "properties": {
    "company": {
      "$ref": "#/definitions/company"
    },
    "status": {
      "default": "found",
      "id": "/properties/status",
      "type": "string"
    },
    "match_request_id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/match_request_id",
      "type": "string"
    },
    "total_count": {
      "id": "/properties/total_count",
      "type": "number"
    }
  },
  "required": [
    "company",
    "status",
    "total_count",
    "match_request_id"
  ],
  "type": "object"
}

=== honeypotio/match_schema/enrich_company_response.example.json
{
  "match_request_id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "total_count": 1,
  "status": "found",
  "company": {
    "name": "Honeypot GmbH",
    "location": [ "Berlin, Germany" ],
    "url": "https://www.honeypot.io",
    "profileUrls": [
      "https://github.com/honeypotio",
      "https://linkedin.com/company/honeypot"
    ],
    "positions": [
      {
        "name": "ruby",
        "description": "4+ years experience with Ruby on Rails and API's"
      }
    ]
  }
}
