=== honeypotio/match_schema/position.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
  },
  "id": "position.schema.json",
  "properties": {
    "description": {
      "id": "/properties/description",
      "type": "string"
    },
    "id": {
      "id": "/properties/id",
      "type": "string"
    },
    "refId": {
      "type": [
        "integer",
        "string"
      ]
    },
    "name": {
      "id": "/properties/name",
      "type": "string"
    },
    "location": {
      "id": "/properties/location",
      "type": "string"
    },
    "department": {
      "id": "/properties/department",
      "type": "string"
    },
    "yearsOfXp": {
      "type": "integer"
    },
    "yearsRelevantXp": {
      "type": "integer"
    },
    "requiredTechnologies": {
      "id": "/properties/requiredTechnologies",
      "items": {
        "id": "/properties/requiredTechnologies/items",
        "type": "string"
      },
      "type": "array"
    },
    "technologies": {
      "id": "/properties/technologies",
      "items": {
        "id": "/properties/technologies/items",
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "name"
  ],
  "type": "object"
}

=== honeypotio/match_schema/examples/position.json
{
  "name": "Senior Ruby Developer",
  "refId": "SNR-Ruby-0431",
  "id": "a03fd159-8b1a-442e-b287-j9hd4280ad5b",
  "location": "Berlin, Germany",
  "department": "Engineering",
  "yearsOfXp": 3,
  "yearsRelevantXp": 3,
  "requiredTechnologies": ["Ruby"],
  "technologies": ["MySql"],
  "description": "You have to be a super rockstar with ruby 50+ years of experience."
}
