=== honeypotio/match_schema/schemas/enrich_person_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "person": {
      "$ref": "file:schemas/person.json"
    }
  },
  "id": "enrich_person_response.schema.json",
  "properties": {
    "person": {
      "$ref": "#/definitions/person"
    },
    "status": {
      "default": "found",
      "id": "/properties/status",
      "type": "string"
    },
    "match_request_id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/match_request_id",
      "type": "string"
    },
    "total_count": {
      "id": "/properties/total_count",
      "type": "number"
    }
  },
  "required": [
    "person", "status", "total_count", "match_request_id"
  ],
  "type": "object"
}

=== honeypotio/match_schema/examples/enrich_person_response.json
{
  "match_request_id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "total_count": 1,
  "status": "found",
  "person": {
    "id": "e78f3057-8b3a-462e-b257-257d5251ad2b",
    "refId": "optional reference id",
    "name": "Hugo Duksis",
    "summary": "Experienced developer interested in functional programming",
    "email": "hugo@honeypot.io",
    "profileUrls": [
      "https://linkedin.com/in/duksis",
      "https://github.com/duksis",
      "https://twitter.com/duksis"
    ],
    "resumeUrl": "https://www.dropbox.com/s/pynm2ro69m51i98/HugoDuksisProfile.pdf?dl=1",
    "skills": ["backbone.js", "react.js", "flux"],
    "experienceEntries": [
      {
        "position": "airbaltic",
        "description": null,
        "custom_company": "flight support specialist",
        "technologies": [],
        "start_year": 2010,
        "end_year": 2013
      },
      {
        "position": "accenture",
        "description": null,
        "custom_company": "web developer",
        "technologies": [],
        "start_year": 2015,
        "end_year": null
      }
    ],
    "educationEntries":[
      {
        "school_name": "TU Berlin",
        "degree": "Bachelor's Degree",
        "discipline": "Computer Science",
        "start_year": 2003,
        "end_year": 2006
      }
    ],
    "publicActivity": {
      "github": {
        "followerCount": 70,
        "starCount": 13
      },
      "twitter": {
        "followerCount": 502
      },
      "stackoverflow": {
        "reputation": 6262
      }
    }
  }
}
