=== honeypotio/match_schema/schemas/enrich_company_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "company": {
      "$ref": "file:schemas/company.json"
    }
  },
  "id": "enrich_company_response.schema.json",
  "properties": {
    "company": {
      "$ref": "#/definitions/company"
    },
    "status": {
      "default": "found",
      "id": "/properties/status",
      "type": "string"
    },
    "match_request_id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/match_request_id",
      "type": "string"
    },
    "total_count": {
      "id": "/properties/total_count",
      "type": "number"
    }
  },
  "required": [
    "company", "status", "total_count", "match_request_id"
  ],
  "type": "object"
}

=== honeypotio/match_schema/examples/enrich_company_response.json
{
  "match_request_id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "total_count": 1,
  "status": "found",
  "company": {
    "name": "Honeypot GmbH",
    "id": "234567876543234567",
    "refId": "optional ref id",
    "location": [ "Berlin, Germany" ],
    "url": "https://www.honeypot.io",
    "profileUrls": [
      "https://github.com/honeypotio",
      "https://linkedin.com/company/honeypot"
    ],
    "positions": [
      {
        "id": "23a8b975-cb34-4804-b8b1-14c194de9fe4",
        "refId": "optional reference id",
        "name": "ruby developer",
        "requiredTechnologies": ["Ruby"],
        "technologies": ["Rails", "API"],
        "yearsOfXp": 3,
        "yearsRelevantXp": 3,
        "description": "4+ years experience with Ruby on Rails and API's"
      }
    ]
  }
}
