=== honeypotio/match_schema/schemas/matcher_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "company": {
      "$ref": "file:schemas/company.json"
    },
    "person": {
      "$ref": "file:schemas/person.json"
    }
  },
  "id": "matcher_request.schema.json",
  "properties": {
    "companies": {
      "additionalItems": false,
      "items": {
        "$ref": "#/definitions/company"
      },
      "type": "array"
    },
    "people": {
      "items": {
        "$ref": "#/definitions/person"
      },
      "type": "array"
    },
    "status": {
      "default": "fulfilled",
      "id": "/properties/status",
      "type": "string"
    },
    "id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/id",
      "type": "string"
    }
  },
  "required": [
    "companies", "status", "people", "id"
  ],
  "type": "object"
}

=== honeypotio/match_schema/examples/matcher_request.json
{
  "id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "status": "fulfilled",
  "people": [
    {
      "id": "e78f3057-8b3a-462e-b257-257d5251ad2b",
      "refId": "optional reference id",
      "name": "Hugo Duksis",
      "summary": "Experienced developer interested in functional programming",
      "email": "hugo@honeypot.io",
      "profileUrls": [
        "https://linkedin.com/in/duksis",
        "https://github.com/duksis",
        "https://twitter.com/duksis"
      ],
      "resumeUrl": "https://www.dropbox.com/s/pynm2ro69m51i98/HugoDuksisProfile.pdf?dl=1",
      "skills": ["backbone.js", "react.js", "flux"],
      "experienceEntries": [
        {
          "position": "airbaltic",
          "description": null,
          "custom_company": "flight support specialist",
          "technologies": [],
          "start_year": 2010,
          "end_year": 2013
        },
        {
          "position": "accenture",
          "description": null,
          "custom_company": "web developer",
          "technologies": [],
          "start_year": 2015,
          "end_year": null
        }
      ],
      "educationEntries":[
        {
          "school_name": "TU Berlin",
          "degree": "Bachelor's Degree",
          "discipline": "Computer Science",
          "start_year": 2003,
          "end_year": 2006
        }
      ],
      "publicActivity": {
        "github": {
          "followerCount": 70,
          "starCount": 13
        },
        "twitter": {
          "followerCount": 502
        },
        "stackoverflow": {
          "reputation": 6262
        }
      }
    }
  ],
  "companies": [
    {
      "name": "Honeypot GmbH",
      "id": "234567876543234567",
      "refId": "optional ref id",
      "location": [ "Berlin, Germany" ],
      "url": "https://www.honeypot.io",
      "profileUrls": [
        "https://github.com/honeypotio",
        "https://linkedin.com/company/honeypot"
      ],
      "positions": [
        {
          "id": "23a8b975-cb34-4804-b8b1-14c194de9fe4",
          "refId": "optional reference id",
          "name": "ruby developer",
          "requiredTechnologies": ["Ruby"],
          "technologies": ["Rails", "API"],
          "yearsOfXp": 3,
          "yearsRelevantXp": 3,
          "description": "4+ years experience with Ruby on Rails and API's"
        }
      ]
    }
  ]
}
