=== honeypotio/match_schema/schemas/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "company": {
      "$ref": "file:schemas/company.json"
    },
    "person": {
      "$ref": "file:schemas/person.json"
    },
    "position": {
      "$ref": "file:schemas/position.json"
    },
    "match": {
      "$ref": "file:schemas/match.json"
    }
  },
  "id": "response.schema.json",
  "properties": {
    "companies": {
      "additionalItems": false,
      "items": {
        "$ref": "#/definitions/company"
      },
      "type": "array"
    },
    "people": {
      "items": {
        "$ref": "#/definitions/person"
      },
      "type": "array"
    },
    "positions": {
      "additionalItems": false,
      "items": {
        "$ref": "#/definitions/position"
      },
      "type": "array"
    },
    "results": {
      "items": {
        "$ref": "#/definitions/match"
      },
      "type": "array"
    },
    "id": {
      "default": "e63fa057-8b3a-462e-b257-257d5251ad2b",
      "id": "/properties/id",
      "type": "string"
    },
    "status": {
      "default": "fulfilled",
      "id": "/properties/status",
      "type": "string"
    }
  },
  "required": [
    "positions",
    "companies",
    "people"
  ],
  "type": "object"
}

=== honeypotio/match_schema/examples/response.json
{
  "id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "status": "fulfilled",
  "results": [
    {
      "score": 0.0396696499,
      "personId": "e78f3057-8b3a-462e-b257-257d5251ad2b",
      "positionId": "ba2383dbba375cebb69c3d7fafd05c29",
      "companyId": "1277b341ec69285d439f4321544497bb",
      "personKeywords": {
        "Ruby": 3,
        "Ember.js": 2,
        "Agile": 1
      },
      "positionKeywords": {
        "Ruby": 5,
        "DevOps": 1
      }
    }
  ],
  "people": [
    {
      "id": "e78f3057-8b3a-462e-b257-257d5251ad2b",
      "refId": "optional reference id",
      "name": "Hugo Duksis",
      "summary": "Experienced developer interested in functional programming",
      "email": "hugo@honeypot.io",
      "profileUrls": [
        "https://linkedin.com/in/duksis",
        "https://github.com/duksis",
        "https://twitter.com/duksis"
      ],
      "resumeUrl": "https://www.dropbox.com/s/pynm2ro69m51i98/HugoDuksisProfile.pdf?dl=1",
      "skills": ["backbone.js", "react.js", "flux"],
      "experienceEntries": [
        {
          "position": "airbaltic",
          "description": null,
          "custom_company": "flight support specialist",
          "technologies": [],
          "start_year": 2010,
          "end_year": 2013
        },
        {
          "position": "accenture",
          "description": null,
          "custom_company": "web developer",
          "technologies": [],
          "start_year": 2015,
          "end_year": null
        }
      ],
      "educationEntries":[
        {
          "school_name": "TU Berlin",
          "degree": "Bachelor's Degree",
          "discipline": "Computer Science",
          "start_year": 2003,
          "end_year": 2006
        }
      ],
      "publicActivity": {
        "github": {
          "followerCount": 70,
          "starCount": 13
        },
        "twitter": {
          "followerCount": 502
        },
        "stackoverflow": {
          "reputation": 6262
        }
      }
    }
  ],
  "positions": [
    {
      "id": "ba2383dbba375cebb69c3d7fafd05c29",
      "refId": "optional reference id",
      "name": "ruby",
      "description": "4+ years experience with Ruby on Rails and API's"
    }
  ],
  "companies": [
    {
      "id": "1277b341ec69285d439f4321544497bb",
      "name": "Honeypot GmbH",
      "location": [ "Berlin, Germany" ],
      "url": "https://www.honeypot.io",
      "profileUrls": [
        "https://github.com/honeypotio",
        "https://linkedin.com/company/honeypot"
      ]
    }
  ]
}

=== honeypotio/match_schema/response.example.json
{
  "id": "e63fa057-8b3a-462e-b257-257d5251ad2b",
  "status": "fulfilled",
  "results": [
    {
      "score": 0.0396696499,
      "personId": "e78f3057-8b3a-462e-b257-257d5251ad2b",
      "positionId": "ba2383dbba375cebb69c3d7fafd05c29",
      "companyId": "1277b341ec69285d439f4321544497bb"
    }
  ],
  "people": [
    {
      "id": "e78f3057-8b3a-462e-b257-257d5251ad2b",
      "refId": "optional reference id",
      "name": "Hugo Duksis",
      "email": "hugo@honeypot.io",
      "resumeUrl": "https://www.dropbox.com/s/pynm2ro69m51i98/HugoDuksisProfile.pdf?dl=1",
      "profileUrls": [
        "https://linkedin.com/in/duksis",
        "https://github.com/duksis",
        "https://twitter.com/duksis"
      ],
      "skills": ["backbone.js", "react.js", "flux"],
      "experienceEntries": [
        {
          "position": "airbaltic",
          "description": null,
          "custom_company": "flight support specialist",
          "technologies": [],
          "start_year": 2010,
          "end_year": 2013
        },
        {
          "position": "accenture",
          "description": null,
          "custom_company": "web developer",
          "technologies": [],
          "start_year": 2015,
          "end_year": null
        }
      ]
    }
  ],
  "positions": [
    {
      "id": "ba2383dbba375cebb69c3d7fafd05c29",
      "refId": "optional reference id",
      "name": "ruby",
      "description": "4+ years experience with Ruby on Rails and API's"
    }
  ],
  "companies": [
    {
      "id": "1277b341ec69285d439f4321544497bb",
      "name": "Honeypot GmbH",
      "location": [ "Berlin, Germany" ],
      "url": "https://www.honeypot.io",
      "profileUrls": [
        "https://github.com/honeypotio",
        "https://linkedin.com/company/honeypot"
      ]
    }
  ]
}
